version: '3'

services:
    setshape-db:
        image: mewgrammer/setshapedb:latest
        restart: always
        ports:
            - 44300:44300
            - 30000:3000
        networks:
            - mainNet
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        networks:
            - mainNet
        environment:
            SA_PASSWORD: "secret_password2019"
            ACCEPT_EULA: "Y"
            MSSQL_PID : "Express"
networks:
    mainNet:
        driver: bridge
